Removed type annotation errors
The following errors are removed with the commit.
manim/mobject/geometry/tips.py:115: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:208: error: Function is missing a type annotation  [no-untyped-def]
manim/mobject/geometry/tips.py:232: error: Function is missing a return type annotation  [no-untyped-def]
manim/mobject/geometry/tips.py:245: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:273: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:282: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:301: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:310: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/tips.py:333: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]

The following errors are still present:
manim/mobject/geometry/tips.py:167: error: Unsupported left operand type for - ("tuple[float, float, float]")  [operator]
manim/mobject/geometry/tips.py:167: note: Both left and right operands are unions
manim/mobject/geometry/tips.py:230: error: Argument 1 to "scale" of "Mobject" has incompatible type "floating[Any]"; expected "float"  [arg-type]