Removed type annotation errors
The following four errors are removed with the commit.
manim/mobject/geometry/labeled.py:63: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
manim/mobject/geometry/labeled.py:70: error: Incompatible default for argument "frame_fill_color" (default has type "None", argument has type "ManimColor | int | str | tuple[int, int, int] | tuple[float, float, float] | <6 more items>")  [assignment]
manim/mobject/geometry/labeled.py:82: error: Incompatible types in assignment (expression has type "MathTex | Text", variable has type "MathTex")  [assignment]
manim/mobject/geometry/labeled.py:150: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]