Import MethodWithArgs, CHOOSE_NUMBER_MESSAGE and INVALID_NUMBER_MESSAGE (#4538)
* Fix error when calling 'manim basic.py'

* Fix error when running "uv run manim basic.py"

NameError: name 'MethodWithArgs' is not defined

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Import Shader, Mesh, FullScreenQuad, OpenGLTexturedSurface and OpenGLSurfaceMeshFix

To handle some missing imports

# Conflicts:
#	example_scenes/opengl.py

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>